// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9NYzgmA0YOVkptOu4jq2nAn_9bd7pPho',
    appId: '1:912024924011:web:6f296e90d247f829a8662e',
    messagingSenderId: '912024924011',
    projectId: 'notes-ai-18bfd',
    authDomain: 'notes-ai-18bfd.firebaseapp.com',
    storageBucket: 'notes-ai-18bfd.firebasestorage.app',
    measurementId: 'G-TQ65V4N70S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqcbEeskug4nA6ahDAfg2zm9OKZEX-AfA',
    appId: '1:912024924011:android:7bf76bc552a74c38a8662e',
    messagingSenderId: '912024924011',
    projectId: 'notes-ai-18bfd',
    storageBucket: 'notes-ai-18bfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOgrDxK3Sx8QM-Cl2xucuFngtEWVOBM7M',
    appId: '1:912024924011:ios:72d41c21c437d970a8662e',
    messagingSenderId: '912024924011',
    projectId: 'notes-ai-18bfd',
    storageBucket: 'notes-ai-18bfd.firebasestorage.app',
    iosBundleId: 'com.example.audioNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOgrDxK3Sx8QM-Cl2xucuFngtEWVOBM7M',
    appId: '1:912024924011:ios:72d41c21c437d970a8662e',
    messagingSenderId: '912024924011',
    projectId: 'notes-ai-18bfd',
    storageBucket: 'notes-ai-18bfd.firebasestorage.app',
    iosBundleId: 'com.example.audioNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9NYzgmA0YOVkptOu4jq2nAn_9bd7pPho',
    appId: '1:912024924011:web:dab3f59e97e79b50a8662e',
    messagingSenderId: '912024924011',
    projectId: 'notes-ai-18bfd',
    authDomain: 'notes-ai-18bfd.firebaseapp.com',
    storageBucket: 'notes-ai-18bfd.firebasestorage.app',
    measurementId: 'G-RZJ8QPXXTC',
  );
}
